// =============================================================================
// sprite_renderer.v -- "is this pixel part of the sprite, and if so, what
// color?" Asked once per pixel, 9 million times per second.
// =============================================================================
//
// How the sprite is stored:
//   The 64x64 sprite lives in a chunk of internal FPGA memory called "block
//   RAM" (BRAM). It's a small RAM block right inside the chip -- separate
//   from regular registers, and very fast.
//
//   When you build the project, Yosys reads rtl/sprite.mem (a text file of
//   4096 hex numbers, generated by tools/png_to_mem.py) and bakes those
//   values into the BRAM. So the sprite image is literally part of the
//   bitstream that gets loaded onto the FPGA.
//
// How a pixel is looked up:
//   1. We get px, py = the screen pixel currently being drawn.
//   2. We get sprite_x, sprite_y = where the sprite's top-left corner is.
//   3. Check if (px, py) is inside the sprite's bounding box.
//   4. If yes, compute local coords: lx = px - sprite_x, ly = py - sprite_y
//      (so lx, ly are 0..63 inside the sprite).
//   5. Look up mem[ly * 64 + lx] -- that's the pixel's color in RGB565.
//   6. If that color is magenta (0xF81F), treat as transparent (in_sprite=0)
//      so the background shows through. Otherwise output the color.
//
// The 1-cycle delay:
//   BRAM reads are *synchronous* -- you put an address in, and one clock
//   later the data comes out. So everything in this module is delayed by
//   one pclk cycle from when (px, py) was valid. top.v compensates by
//   delaying its DEN signal by one cycle too, so everything stays aligned.
//
// Why use magenta as transparent?
//   "Chroma key" -- same trick as a green-screen movie. We pick a color
//   that's unlikely to appear in real art (bright magenta) and declare:
//   "any pixel of this exact color = see-through". This is much cheaper
//   than storing a separate alpha channel.
// =============================================================================

module sprite_renderer #(
    parameter        MEM_FILE          = "rtl/sprite.mem",
    parameter [9:0]  W                 = 10'd64,   // sprite width
    parameter [9:0]  H                 = 10'd64,   // sprite height
    parameter        NUM_FRAMES        = 4,        // number of animation frames in ROM
    parameter        FRAME_BITS        = 2,        // = $clog2(NUM_FRAMES)
    parameter [15:0] TRANSPARENT_COLOR = 16'hF81F  // RGB565 pure magenta
) (
    input  wire                   pclk,
    input  wire [9:0]             px,           // current screen pixel x
    input  wire [9:0]             py,           // current screen pixel y
    input  wire [9:0]             sprite_x,     // sprite's top-left x on the screen
    input  wire [9:0]             sprite_y,     // sprite's top-left y on the screen
    input  wire [FRAME_BITS-1:0]  frame_index,  // which animation frame to show
    output wire                   in_sprite,    // 1 if pixel is inside sprite AND not transparent
    output wire [4:0]             r,
    output wire [5:0]             g,
    output wire [4:0]             b
);

    // ----- The sprite ROM: NUM_FRAMES * 4096 entries (64x64 each), 16 bits per pixel -----
    // Frames are laid out one after another: frame 0 at addrs [0..4095],
    // frame 1 at [4096..8191], etc. png_to_mem.py concatenates them in order.
    reg [15:0] mem [0:NUM_FRAMES*4096 - 1];
    initial $readmemh(MEM_FILE, mem);

    // ----- Bounding box test (in screen coordinates) -----
    wire inside_bbox = (px >= sprite_x) && (px < sprite_x + W) &&
                       (py >= sprite_y) && (py < sprite_y + H);

    // ----- Convert screen coords to sprite-local coords (0..63) -----
    // Subtraction in 10-bit, then take the low 6 bits. The low-6 step is
    // only valid when we ARE inside the box; outside, we ignore the result.
    wire [9:0] lx_full = px - sprite_x;
    wire [9:0] ly_full = py - sprite_y;
    wire [5:0] lx = lx_full[5:0];
    wire [5:0] ly = ly_full[5:0];

    // The address into the ROM: {frame, row, column}. Total width = FRAME_BITS + 12.
    wire [FRAME_BITS+11:0] addr = {frame_index, ly, lx};

    // ----- Synchronous BRAM read (this is the 1-cycle delay) -----
    // pixel_q  = the RGB565 color sitting at this address
    // inside_q = the bounding-box flag, also delayed 1 cycle to stay aligned
    reg [15:0] pixel_q;
    reg        inside_q;
    always @(posedge pclk) begin
        pixel_q  <= mem[addr];
        inside_q <= inside_bbox;
    end

    // ----- Final outputs: chroma-key check + split RGB565 into R, G, B -----
    assign in_sprite = inside_q && (pixel_q != TRANSPARENT_COLOR);
    assign r         = pixel_q[15:11];   // top 5 bits = red
    assign g         = pixel_q[10:5];    // middle 6 bits = green
    assign b         = pixel_q[4:0];     // bottom 5 bits = blue

endmodule
